apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-config-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-config
  template:
    metadata:
      labels:
        app: app-config
    spec: 
      containers:
        - name: app-config
          image: 1stnano/app-config:latest
          env:
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: 'development'
          readinessProbe:
            httpGet:
              path: /api/v1/app/cfg/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/app/cfg/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: app-config-srv
spec:
  selector:
    app: app-config
  ports:
    - name: app-config
      protocol: TCP
      port: 3000
      targetPort: 3000